services:
  api:
    build:
      context: ./backend
    container_name: verae_api
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=ironrisk_bi_reg_29n.cbm
      - MODEL_PATH=/workspace/ironrisk_bi_reg_29n.cbm
    volumes:
      - ./:/workspace:ro

  frontend:
    build:
      context: ./frontend
    container_name: verae_frontend
    ports:
      - "8080:80"
    depends_on:
      - api
